import { db, doc, setDoc, increment, onSnapshot } from './firebase.js';

// Global variables for the game state
let quizBonusTime = 0;
let baseTime = 60; 
let gameStarted = false;

// --- 1. QUIZ PHASE (Runs First) ---

async function initGameFlow() {
    try {
        // Fetch the questions generated by the AI
        const response = await fetch('questions.json');
        if (!response.ok) throw new Error("No questions file found");
        const questions = await response.json();
        
        startQuiz(questions);
    } catch (err) {
        console.warn("Skipping quiz: questions.json not found. Starting game...");
        launchUnityGame();
    }
}

function startQuiz(questions) {
    const modal = document.getElementById('questionModal');
    if (!modal) {
        launchUnityGame();
        return;
    }

    modal.style.display = 'flex';
    let currentQ = 0;

    function renderQuestion() {
        if (currentQ >= questions.length) {
            modal.style.display = 'none';
            launchUnityGame();
            return;
        }

        const qData = questions[currentQ];
        document.getElementById('questionText').textContent = qData.q;
        
        // Clear old buttons and add new ones (A, B, C, D)
        const container = document.getElementById('optionsContainer');
        container.innerHTML = '';
        
        qData.options.forEach((opt, idx) => {
            const btn = document.createElement('button');
            btn.textContent = opt;
            btn.className = 'option-btn';
            btn.onclick = () => {
                if (idx === qData.correct) {
                    quizBonusTime += 5; // Add 5 seconds for correct answer
                    console.log("Correct! +5 seconds added.");
                }
                currentQ++;
                renderQuestion();
            };
            container.appendChild(btn);
        });
    }
    renderQuestion();
}

// --- 2. UNITY GAME PHASE ---

function launchUnityGame() {
    gameStarted = true;
    const finalStartTime = baseTime + quizBonusTime;
    console.log(`Unity Game Starting! Total time: ${finalStartTime}s`);
    
    // If you have a timer element on screen, set it here
    const timerEl = document.getElementById("timeLeft");
    if (timerEl) timerEl.textContent = finalStartTime;
}

// --- 3. MULTIPLAYER & FIREBASE (The critical stuff) ---

document.addEventListener("DOMContentLoaded", () => {
    const sessionPin = localStorage.getItem("sessionPin") || "DEFAULT_SESSION";
    const sessionRef = doc(db, "sessions", sessionPin);

    // LIVE MULTIPLAYER SCORE SYNC
    onSnapshot(sessionRef, (docSnap) => {
        if (docSnap.exists()) {
            const data = docSnap.data();
            if (document.getElementById("scoreA")) document.getElementById("scoreA").textContent = data.teamAScore || 0;
            if (document.getElementById("scoreB")) document.getElementById("scoreB").textContent = data.teamBScore || 0;
        }
    });

    // Start the whole flow (Quiz -> Game)
    initGameFlow();
});

// CATCH SCORE FROM UNITY & SEND TO FIREBASE
document.addEventListener('unityGameOver', async function(e) {
    const finalScore = e.detail.score;
    const team = localStorage.getItem("team") || "A";
    const playerName = localStorage.getItem("playerName") || "UnknownPlayer";
    const sessionPin = localStorage.getItem("sessionPin") || "DEFAULT_SESSION";

    try {
        const sessionRef = doc(db, "sessions", sessionPin);
        
        // Update Team Total
        const updateObj = {};
        updateObj[team === "A" ? "teamAScore" : "teamBScore"] = increment(finalScore);
        await setDoc(sessionRef, updateObj, { merge: true });

        // Update Individual Player Stats
        const playerRef = doc(db, "sessions", sessionPin, "players", playerName);
        await setDoc(playerRef, { score: increment(finalScore), team: team }, { merge: true });
        
        console.log("Score pushed to Firebase successfully!");
    } catch (error) {
        console.error("Firebase error: ", error);
    }
});